### ISSUE TITLE
Use chord layout for visualization?

### ISSUE THREAD

**Issue by cmaes** [EmilienDupont/kidneyExchange#10]
Could we use a chord layout
https://github.com/mbostock/d3/wiki/Chord-Layout
http://bl.ocks.org/mbostock/1046712
http://bost.ocks.org/mike/uberdata/
for the visualization? 

Maybe each of the arcs on the outside could be the different categories. We could draw an edge between arc/categories for each donor-recipient pair.

**Comment by cmaes** [comment]
I guess the question is if you use a chord layout, how do you visualize the final solution that matches patients to donors?

**Comment by cmaes** [comment]
What if it started out as a chord diagram. And then once you clicked compute, we drew the individual edges that defined a transplant using something like this:
http://bl.ocks.org/mbostock/1044242

**Comment by EmilienDupont** [comment]
I've already experimented with chord layouts for this example actually, but I found a few problems. First of all, each "slice" of the the chord layout needs to have two colors, since each slice will represent a donor/recipient pair. When you add in the connections this often makes the plot look awkward and unclear. 
Second of all, it is harder to see that we create cycles on those plots. When you do the force layout the cycles "pop out" and separate, but with chord layouts it often looks quite messy, and doesn't look like cycles.
So I think force layouts work a bit better for this example, but maybe I should try to experiment more with chord layouts too.

**Comment by cmaes** [comment]
My idea is that each slice represents a single group of recipients. So we have a slice for each of the types of recipients. We draw a directed chord from one slice to another slice of a different type to represent the number of donors of that type paired with the original group of recipients.

I think this a good way to visualize the matrix you have now. But it may not be the best way to visualize the final solution with the cycles.

**Comment by cmaes** [comment]
Here is gist I threw together to illustrate what I was thinking.

http://bl.ocks.org/cmaes/2018b2ce4f51409030de

**Comment by cmaes** [comment]
With text for the slice labels
http://bl.ocks.org/cmaes/2018b2ce4f51409030de/a9b45a41ae553921e60cdab374cffb27de768371

**Comment by cmaes** [comment]
After playing with this more, I find it a bit difficult to understand what the chord layout is showing.  I think you're initial assessment is right that a chord layout won't work. I'll try a few more things. But if those don't help, I'll give up on the chord layout idea.
