### ISSUE TITLE
Error: Invalid value for <path> attribute

### ISSUE THREAD

**Issue by cmaes** [EmilienDupont/kidneyExchange#13]
![image](https://cloud.githubusercontent.com/assets/883291/9550495/b6068d26-4d79-11e5-860d-2a6c9bbfb56d.png)

**Comment by EmilienDupont** [comment]
This error comes from drawing the cycles after computing a solution. In most examples of force layouts, links in the graph are lines. But because we want to represent 2 cycles, the links need to be curved, so we have to draw a path. So the links are paths, and the error comes from apparently giving undefined coordinates in lines 519-543 (in the start() function) to draw the path. I'm not sure about the exact origin of the error, but it doesn't seem to affect the visualization.
